### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by JonDigital16** [SamK/wefunk_dl#5]
When attempting to run updated script receive Permission Denied Error.

<img width="581" alt="Screenshot 2024-12-02 at 10 19 15 AM" src="https://github.com/user-attachments/assets/db8f3263-2fbe-4209-9ad5-673028ebf2d3">

**Comment by honnet** [comment]
It still works for me on linux...

=> Did you try asking [claude.ai](https://claude.ai) (or other LLMs), they have surprisingly good tips...

**Comment by JonDigital16** [comment]
Thank you.  That helped alot!
