### ISSUE TITLE
CRITICAL: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by JonDigital16** [SamK/wefunk_dl#6]
For any show starting at 168 up to 1122 produces the following error.  

<img width="668" alt="Screenshot 2024-12-05 at 10 56 09 AM" src="https://github.com/user-attachments/assets/fa332b80-d571-4720-9fdd-f5db92701604">

**Comment by SamK** [comment]
Hi, I'm closing this issue in favor of #4.
